/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/cards/GameCardMain copy.vue')['default']
    GameCard: typeof import('./src/components/cards/GameCard.vue')['default']
    GameCardHand: typeof import('./src/components/cards/GameCardHand.vue')['default']
    GameCardMain: typeof import('./src/components/cards/GameCardMain.vue')['default']
    GameCardMaster: typeof import('./src/components/cards/GameCardMaster.vue')['default']
    GameCardOut: typeof import('./src/components/cards/GameCardOut.vue')['default']
    GameIcons: typeof import('./src/components/GameIcons.vue')['default']
    GameMain: typeof import('./src/components/GameMain.vue')['default']
    GameSet: typeof import('./src/components/GameSet.vue')['default']
    GameStart: typeof import('./src/components/GameStart.vue')['default']
    IconFervent: typeof import('./src/components/icons/IconFervent.vue')['default']
    IconMask: typeof import('./src/components/icons/IconMask.vue')['default']
    IconRaptor: typeof import('./src/components/icons/IconRaptor.vue')['default']
    IconSkeleton: typeof import('./src/components/icons/IconSkeleton.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTriangle: typeof import('./src/components/icons/IconTriangle.vue')['default']
    IconValv: typeof import('./src/components/icons/IconValv.vue')['default']
  }
}
