/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GameCardHand: typeof import('./src/components/cards/GameCardHand.vue')['default']
    GameCardMain: typeof import('./src/components/cards/GameCardMain.vue')['default']
    GameCardMaster: typeof import('./src/components/cards/GameCardMaster.vue')['default']
    GameIcons: typeof import('./src/components/GameIcons.vue')['default']
    GameMain: typeof import('./src/components/GameMain.vue')['default']
    GameStart: typeof import('./src/components/GameStart.vue')['default']
    IconAttack: typeof import('./src/components/icons/IconAttack.vue')['default']
    IconBear: typeof import('./src/components/icons/IconBear.vue')['default']
    IconCloud: typeof import('./src/components/icons/IconCloud.vue')['default']
    IconDesolate: typeof import('./src/components/icons/IconDesolate.vue')['default']
    IconDragon: typeof import('./src/components/icons/IconDragon.vue')['default']
    IconFervent: typeof import('./src/components/icons/IconFervent.vue')['default']
    IconFly: typeof import('./src/components/icons/IconFly.vue')['default']
    IconGroup: typeof import('./src/components/icons/IconGroup.vue')['default']
    IconGroupShadow: typeof import('./src/components/icons/IconGroupShadow.vue')['default']
    IconHeart: typeof import('./src/components/icons/IconHeart.vue')['default']
    IconLion: typeof import('./src/components/icons/IconLion.vue')['default']
    IconMask: typeof import('./src/components/icons/IconMask.vue')['default']
    IconMask2: typeof import('./src/components/icons/IconMask2.vue')['default']
    IconMelankolio: typeof import('./src/components/icons/IconMelankolio.vue')['default']
    IconRaptor: typeof import('./src/components/icons/IconRaptor.vue')['default']
    IconRegroup: typeof import('./src/components/icons/IconRegroup.vue')['default']
    IconShield: typeof import('./src/components/icons/IconShield.vue')['default']
    IconSkeleton: typeof import('./src/components/icons/IconSkeleton.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTotem: typeof import('./src/components/icons/IconTotem.vue')['default']
    IconTotem2: typeof import('./src/components/icons/IconTotem2.vue')['default']
    IconTree: typeof import('./src/components/icons/IconTree.vue')['default']
    IconTriangle: typeof import('./src/components/icons/IconTriangle.vue')['default']
    IconValv: typeof import('./src/components/icons/IconValv.vue')['default']
  }
}
